version: '3.1'

services:
  authentication_api:
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: postgres
      POSTGRESS_DB: postgres
      POSTGRESS_HOST: database
      POSTGRESS_PORT: 5432
    depends_on:
      - database
    image: williamcustodio/udagram_authentication_api:latest
    restart: always
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: postgres:latest
    restart: always
  feed_api:
    depends_on:
      - authentication_api
      - database
    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: postgres
      POSTGRESS_DB: postgres
      POSTGRESS_HOST: database
      POSTGRESS_PORT: 5432
      AUTHENTICATION_API_HOST: database
    image: williamcustodio/udagram_feed_api:latest
    restart: always
  proxy_api:
    depends_on:
      - authentication_api
      - feed_api
      - user_api
    environment:
      AUTHENTICATION_API_HOST: authentication_api
      FEED_API_HOST: feed_api
      USER_API_HOST: user_api
    image: williamcustodio/udagram_proxy_api:latest
    ports:
      - 8080:8080
    restart: always
  user_api:
    depends_on:
      - authentication_api
      - database
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: postgres
      POSTGRESS_DB: postgres
      POSTGRESS_HOST: database
      POSTGRESS_PORT: 5432
      AUTHENTICATION_API_HOST: authentication_api
    image: williamcustodio/udagram_user_api:latest
    restart: always
