apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: udagram-application
  template:
    metadata:
      labels:
        name: udagram-application
        version: 1.0.0
        component: frontend
    spec:
      containers:
        - name: udagram-application-container
          image: williamcustodio/udagram_application:latest
          ports:
            - containerPort: 4200
